name: "Notify new issue to slack"
on:
  issues:
    types: [opened]
jobs:
  Notify_new_issue_to_slack:
    runs-on: ubuntu-latest
    steps:
    - name: Notify Issue Build
      uses: 8398a7/action-slack@v3.8.0
      status: custom
      custom_payload: 
         {
          text: "Custom Field Check",
          attachments: [{
            fallback: 'fallback',
            color: 'good',
            title: 'CI Result',
            text: 'Succeeded',
            fields: [{
              title: 'lower case',
              value: 'LOWER CASE CHECK'.toLowerCase(),
              short: true
            },
            {
              title: 'reverse',
              value: 'gnirts esrever'.split('').reverse().join(''),
              short: true
            },
            {
              title: 'long title1',
              value: 'long value1',
              short: false
            }],
            actions: [{
            }]
          }]
        }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
