name: "Notify new issue to slack"
on:
  issues:
    types: [opened]
jobs:
  Notify_new_issue_to_slack:
    runs-on: ubuntu-latest
    steps:
    - name: Notify Issue Build
      uses: 8398a7/action-slack@v3.8.0
      with:
        status: custom
        fields: workflow,job,commit,repo,ref,author,took
        custom_payload: |
          {
            attachments: [{
              title: 'new issue comming!'
              color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
              text: `${{ github.event.issue.url }}`,
            }]
          }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()

